export const PRODUCTS_SUCCESS = 'PRODUCTS_SUCCESS'
export const PRODUCTS_FAIL = 'PRODUCTS_FAIL'

export const RANDOM_PRODUCT_SUCCESS = 'RANDOM_PRODUCT_SUCCESS'
export const RANDOM_PRODUCT_FAIL = 'RANDOM_PRODUCT_FAIL'

export const COMPANIES_SUCCESS = "COMPANIES_SUCCESS"
export const COMPANIES_FAIL = "COMPANIES_FAIL"

export const CATEGORIES_SUCCESS = "CATEGORIES_SUCCESS"
export const CATEGORIES_FAIL = "CATEGORIES_FAIL"

export const PRODUCTS1_SUCCESS = 'PRODUCTS1_SUCCESS'
export const PRODUCTS1_FAIL = 'PRODUCTS1_FAIL'